workspace:
  base: /go
  path: src/github.com/schrodit/drone-git-version

pipeline:

  deps:
    image: golang:1.9
    pull: true
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
  
  test:
    image: golang:1.9
    commands:
      - go test -cover

  build:
    image: golang:1.9
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - go build -o git-version
      - ls

  publish:
    image: schrodit/drone-git-version
    pull: true
    repo: schrodit/drone-helm
    secrets: [ docker_username, docker_password ]
    usegittag: true
    latest: true
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    when:
      event: [tag]
      branch: master